version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.17.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false